// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_golden_killer = "CgkIyfiOt6EBEAIQBA"; // <GPGSID>
        public const string event_on_purchase = "CgkIyfiOt6EBEAIQDw"; // <GPGSID>
        public const string achievement_silver_killer = "CgkIyfiOt6EBEAIQAw"; // <GPGSID>
        public const string achievement_bronze_sheild_master = "CgkIyfiOt6EBEAIQBQ"; // <GPGSID>
        public const string achievement_golden_sheild_master = "CgkIyfiOt6EBEAIQBw"; // <GPGSID>
        public const string achievement_bronze_killer = "CgkIyfiOt6EBEAIQAg"; // <GPGSID>
        public const string achievement_first_shopper = "CgkIyfiOt6EBEAIQCA"; // <GPGSID>
        public const string achievement_first_kill = "CgkIyfiOt6EBEAIQAQ"; // <GPGSID>
        public const string achievement_super_spender = "CgkIyfiOt6EBEAIQDQ"; // <GPGSID>
        public const string achievement_silver_sheild_master = "CgkIyfiOt6EBEAIQBg"; // <GPGSID>
        public const string achievement_first_spend = "CgkIyfiOt6EBEAIQCw"; // <GPGSID>
        public const string leaderboard_level_up = "CgkIyfiOt6EBEAIQDg"; // <GPGSID>
        public const string achievement_supper_shopper = "CgkIyfiOt6EBEAIQCg"; // <GPGSID>
        public const string achievement_big_spender = "CgkIyfiOt6EBEAIQDA"; // <GPGSID>
        public const string achievement_big_shopper = "CgkIyfiOt6EBEAIQCQ"; // <GPGSID>

}

